### ISSUE TITLE
[Traefik Pilot] Traefik Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [dclairac/traefik-plugin-headers#2]
The plugin was not imported into Traefik Pilot.

Cause:
```
failed to get manifest: GET https://api.github.com/repos/dclairac/traefik-plugin-headers/contents/.traefik.yml?ref=v0.1.1: 502  []
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.containo.us/).

**Comment by dclairac** [comment]
There was no change on my repo.
A 502 (only one time) should not lead to disable plugin
